on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

name: lint

permissions:
  contents: read

jobs:
  lint:
    name: Lint Module
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Setup Repo
      shell: bash
      run: |
        mkdir -p ~/.local/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.local/bin/repo
        chmod +x ~/.local/bin/repo
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install ASDF
      uses: asdf-vm/actions/setup@v3
      with:
        asdf_branch: v0.14.1
    - name: Configure LCAF
      shell: bash
      run: |
        git config --add user.name github_actions
        git config --add user.email actions_noreply@github.com
        make configure
        make tfmodule/create_example_providers
        make tfmodule/init
    - name: Lint Repository
      shell: bash
      run: |
        go build ./...
        GO_LINT_TIMEOUT=10m make lint
